// Get Request
GET http://localhost:8080/

###

GET http://localhost:8080/api/entry

### add Entry

POST http://localhost:8080/api/entry/add
Content-Type: application/json

{
    "weight": 250.0,
    "reps": 8,
    "username": "testuser",
    "exerciseName": "Deadlift"
}

### change Entry
PUT http://localhost:8080/api/entry/change
Content-Type: application/json

{
    "id": 1,
    "weight": 10000.0,
    "reps": 8
}

### Delete Entry

DELETE http://localhost:8080/api/entry/1

### Register

POST http://localhost:8080/api/users/register
Content-Type: application/json

{
    "username": "testuser",
    "email": "testuser@example.com",
    "password": "password123"
}
### Login
POST http://localhost:8080/api/users/login
Content-Type: application/json

{
    "username": "testuser",
    "password": "password123"
}

### Update Display Name
PUT http://localhost:8080/api/users/updateDisplayName
Content-Type: application/json

{
    "username": "testuser",
    "displayName": "New Display Name"
}